version: 2.1
workflows:
  version: 2
  pull_request_workflow:
    jobs:
      - pull_request_job:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  release_workflow:
    jobs:
      - release_job:
          filters:
            tags:
              only: /.*/

jobs:
  pull_request_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            # Add your pull request specific commands here
  release_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Release Job
          command: |
            # Add your release specific commands here
