version: 2.1

filters: 
  - &common_filter
    tags:
      only: /^v[0-9]+\.[0-9]+\.[0-9]+(-(sc|rc).*)?$/
  - &sprint_filter
    branches:
      only: /^SPRINT\/.*/
    tags:
      only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+(?:-(sc|rc).*)?$/

workflows:
  version: 2
  sprint_release_workflow:
    jobs:
      - lint-dockerfile-api:
          filters:
            tags:
              only: /.*/
      - build-image:
          rails_env: development
          requires:
            - "lint-dockerfile-api"
          filters: *common_filter
      - build-prod:
          requires:
            - "lint-dockerfile-api"
          filters: *sprint_filter
      - api-rspec:
          requires:
            - "build-image"
          filters: *common_filter
      - test-api-rubocop:
          requires:
            - "build-image"
          filters: *common_filter
      - test-api-brakeman:
          requires:
            - "build-image"
          filters: *sprint_filter
      - test-api-bundler-audit:
          requires:
            - "build-image"
          filters: *sprint_filter
      - test-scan-api:
          requires:
            - "build-prod"
          filters: *sprint_filter
      - build-dev-schema:
          requires:
            - "test-api-brakeman"
            - "test-api-bundler-audit"
            - "test-api-rubocop"
            - "test-scan-api"
            - "api-rspec"
          filters:
            branches:
              ignore:
                - /^SPRINT\/.*/
                - /main/
      - build-prod-schema:
          requires:
            - "test-api-brakeman"
            - "test-api-bundler-audit"
            - "test-api-rubocop"
            - "test-scan-api"
            - "api-rspec"
          filters: *sprint_filter
      - tag_tested_production:
          requires:
            - "build-prod-schema"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+(?:-(sc|rc).*)?$/
              
jobs:
  lint-dockerfile-api:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the lint lint-dockerfile-api Job"
  build-image:
    parameters:
      rails_env:
        type: string
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the build Job for << pipeline.parameters.rails-env >>"
  build-dev:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the build dev Job"
  build-prod:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the build prod Job"
  api-rspec:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the api-rspec Job"
  test-api-brakeman:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the test-api-brakeman Job"
  test-api-bundler-audit:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the test-api-bundler-audit Job"
  test-api-rubocop:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the test-api-rubocop Job"
  test-scan-api:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the test-scan-api Job"
  build-dev-schema:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the build-dev-schema Job"
  build-prod-schema:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the build-prod-schema Job"
  tag_tested_production:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "docker tag your-image:latest your-image:$CIRCLE_TAG"
