version: 2.1
orbs:
  sample: av-lasse/sample@dev:fde2f10e7e901b47580d7900bb58eb5c64ac1302
  gh-cli: circleci/github-cli@2.2.0

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh-cli/install:
          version: 2.29.0
      - gh-cli/setup
      - sample/release

workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
          context:
            - GITHUB_CREDS

