version: 2.1
orbs:
  sample: av-lasse/sample@dev:fb7ca557e3216728912a5df60b9cabda8c10a463
  gh-cli: circleci/github-cli@2.2.0

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh-cli/setup
      - sample/release

workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
          context:
            - GITHUB_CREDS

