version: 2.1
workflows:
  version: 2
  sprint_release_workflow:
    jobs:
      - lint-dockerfile-api
      - build-dev:
          requires:
            - "lint-dockerfile-api"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - build-prod:
          requires:
            - "lint-dockerfile-api"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - api-rspec:
          requires:
            - "build-dev"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - test-api-rubocop:
          requires:
            - "api-rspec"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - test-api-brakeman:
          requires:
            - "api-rspec"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - test-api-bundler-audit:
          requires:
            - "api-rspec"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - test-scan-api:
          requires:
            - "build-prod"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - build-dev-schema:
          requires:
            - "test-api-brakeman"
            - "test-apibundler-audit"
            - "test-api-rubocop-api"
            - "test-scan-api"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - build-prod-schema:
          requires:
            - "test-api-brakeman"
            - "test-apibundler-audit"
            - "test-api-rubocop-api"
            - "test-scan-api"
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - tag_tested_develop:
          requires:
            - "build-dev-schema"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - tag_tested_production:
          requires:
            - "build-prod-schema"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
              
jobs:
  build-dev:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the build dev Job"
  build-prod:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the build prod Job"
  api-rspec:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the api-rspec Job"
  test-api-brakeman:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            echo "This is the test-api-brakeman Job"
  test-api-bundler-audit:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the test-api-bundler-audit Job"
  test-api-rubocop:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the test-api-rubocop Job"
  test-scan-api:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the test-scan-api Job"
  build-dev-schema:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the build-dev-schema Job"
  build-prod-schema:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the build-prod-schema Job"
  tag_tested_develop:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the tag_tested_develop Job"
  tag_tested_production:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            echo "This is the tag_tested_production Job"