version: 2.1
workflows:
  version: 2
  pull_request_workflow:
    jobs:
      - pull_request_job:
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
  prod_release_workflow:
    jobs:
      - prod_release_job:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+$/

jobs:
  pull_request_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            # Add your pull request specific commands here
            echo "This is the Pull Request Job"

  release_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Release Job
          command: |
            # Add your release specific commands here
            echo "This is the Release Job"
