version: 2.1
orbs:
  sample: av-lasse/sample@dev:738ac285d2955ba432fdc549a16e5acb8b82c59a
  gh-cli: circleci/github-cli@2.2.0

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh-cli/setup
      - sample/release

workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
          context:
            - GITHUB_CREDS

