version: 2.1
workflows:
  version: 2
  prod_release_workflow:
    jobs:
      - prod_release_job:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+$/
  sprint_release_workflow:
    jobs:
      - build:
          filters:
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
      - test1:
          requires:
            - "build"
      - test2:
          requires:
            - "build"
      - sprint_release_job:
          requires:
            - "test1"
            - "test2"
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9])+\-sc(.*)$/
              
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            # Add your pull request specific commands here
            echo "This is the build Job"
  test1:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            # Add your pull request specific commands here
            echo "This is the test1 Job"
  test2:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: build
          command: |
            # Add your pull request specific commands here
            echo "This is the test2 Job"
  pull_request_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Pull Request Job
          command: |
            # Add your pull request specific commands here
            echo "This is the Pull Request Job"

  prod_release_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Release Job
          command: |
            # Add your release specific commands here
            echo "This is the Release Job, I will tag docker with $CIRCLE_TAG"
  sprint_release_job:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Release Job
          command: |
            # Add your release specific commands here
            echo "This is the Release Job, I will tag docker with $CIRCLE_TAG"
