version: '2.1'
orbs:
  sample: av-lasse/sample@dev:0ab3664acc0b444746640a0fc71a10fa92c2a300
  gh-cli: circleci/github-cli@2.2.0

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - gh-cli/setup
      - sample/release

workflows:
  use-my-orb:
    jobs:
      - release:
        context: GITHUB_CREDS
        filters:
          branches:
            only:
              - main

