version: 2.1
orbs:
  sample: av-lasse/sample@dev:f3aeccf12f28a675300ae45b08ef0e410a6aa76e

jobs:
  release:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - sample/release
  tag:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - sample/tag

workflows:
  release:
    jobs:
      - release:
          filters:
            branches:
              only:
                - main
          context:
            - GITHUB_CREDS
  tag:
    jobs:
      - tag:
          filters:
            branches:
              ignore:
                - main
          context:
            - GITHUB_CREDS
